import type { FastifyInstance } from "fastify";
import multipart from "@fastify/multipart";
import { authRoutes } from "./auth.js";
import { expensesRoutes } from "./expenses.js";
import { receiptsRoutes } from "./receipts.js";
import { exportRoutes } from "./export.js";
import { insightsRoutes } from "./insights.js";
import { categoriesRoutes } from "./categories.js";
import { budgetsRoutes } from "./budgets.js";
import { tagsRoutes } from "./tags.js";
import { statementsRoutes } from "./statements.js";
import { subscriptionsRoutes } from "./subscriptions.js";
import { monthlyReviewRoutes } from "./monthly-review.js";
import { auditRoutes } from "./audit.js";
import { accessRoutes } from "./access.js";
import { accountsRoutes } from "./accounts.js";
import { alertsRoutes } from "./alerts.js";
import { capturesRoutes } from "./captures.js";
import { reconciliationRoutes } from "./reconciliation.js";
import { smartRulesRoutes } from "./smart-rules.js";
import { ruleSuggestionsRoutes } from "./rule-suggestions.js";
import { settlementRoutes } from "./settlement.js";
import { opsRoutes } from "./ops.js";
import { installCsrfOriginGuard } from "./csrf.js";

export async function dashboardRoutes(app: FastifyInstance) {
  await installCsrfOriginGuard(app);
  await app.register(multipart);
  await app.register(authRoutes);
  await app.register(expensesRoutes);
  await app.register(receiptsRoutes);
  await app.register(exportRoutes);
  await app.register(insightsRoutes);
  await app.register(categoriesRoutes);
  await app.register(budgetsRoutes);
  await app.register(tagsRoutes);
  await app.register(statementsRoutes);
  await app.register(subscriptionsRoutes);
  await app.register(monthlyReviewRoutes);
  await app.register(auditRoutes);
  await app.register(accessRoutes);
  await app.register(accountsRoutes);
  await app.register(alertsRoutes);
  await app.register(capturesRoutes);
  await app.register(reconciliationRoutes);
  await app.register(smartRulesRoutes);
  await app.register(ruleSuggestionsRoutes);
  await app.register(settlementRoutes);
  await app.register(opsRoutes);
}
